name: Build and Test iOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
        
    - name: List Xcode Schemes
      run: xcodebuild -workspace Zodiaccurate.xcworkspace -list
        
    - name: Build iOS App
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_PASSWORD: ${{ secrets.FIREBASE_PASSWORD }}
      run: |
        xcodebuild -workspace Zodiaccurate.xcworkspace \
                   -scheme Zodiaccurate \
                   -destination 'platform=iOS Simulator,name=iPhone 16' \
                   build
                   
    - name: Test iOS App
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_PASSWORD: ${{ secrets.FIREBASE_PASSWORD }}
      run: |
        xcodebuild -workspace Zodiaccurate.xcworkspace \
                   -scheme Zodiaccurate \
                   -destination 'platform=iOS Simulator,name=iPhone 16' \
                   test 